# Generated by Django 4.0.6 on 2022-07-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_propaganda', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='fotos')),
                ('titulo', models.CharField(max_length=150)),
                ('text_button', models.CharField(max_length=150)),
                ('info1', models.CharField(max_length=50)),
                ('info2', models.CharField(max_length=50)),
                ('info3', models.CharField(max_length=50)),
            ],
        ),
    ]
