# Generated by Django 4.0.6 on 2022-07-16 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_navespace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField()),
                ('endereco', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Depoimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_pessoa', models.ImageField(upload_to='pessoas')),
                ('nome', models.CharField(max_length=50)),
                ('comentario', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_produto', models.CharField(max_length=20)),
                ('img_produto', models.ImageField(upload_to='produtos')),
                ('text_button', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Propaganda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('text1', models.CharField(max_length=100)),
                ('text2', models.CharField(max_length=100)),
                ('text3', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Quemsomos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('text_fundador', models.CharField(max_length=50)),
                ('img_fundador', models.ImageField(upload_to='foca')),
                ('text_cargo', models.CharField(max_length=50)),
                ('historia', models.TextField()),
                ('text_frase', models.CharField(max_length=150)),
                ('text_autor', models.CharField(max_length=20)),
            ],
        ),
    ]
